character_map = {
    '†': 'Option + X',
    '©': 'Option + C',
    '√': 'Option + V',
    '∫': 'Option + B',
    '˜': 'Option + N',
    'µ': 'Option + M',
    '¬': 'Option + L',
    'Ø': 'Option + O',
    'Å': 'Option + A',
    'ª': 'Option + J',
    '∞': 'Option + G',
    'ƒ': 'Option + F',
    '∂': 'Option + D',
    'ß': 'Option + S',
    '≤': 'Option + <',
    '≥': 'Option + Shift + >',
    '•': 'Option + .',
    '´': 'Option + 8',
    '«': 'Option + 1',
    '“': 'Option + 2',
    '‘': 'Option + 3',
    '¥': 'Option + 4',
    '~': 'Option + 5',
    '‹': 'Option + 6',
    '÷': 'Option + 7',
    '`': 'Option + 9',
    '≠': 'Option + 0',
    '¡': 'Option + \'',
    'ˆ': 'Option + ì',
    '„': 'Option + Q',
    'Ω': 'Option + W',
    '€': 'Option + E',
    '®': 'Option + R',
    '™': 'Option + T',
    'Æ': 'Option + Y',
    '¨': 'Option + U',
    '∏': 'Option + 4',
    '∆': 'Option + H',
    'ª': 'Option + J',
    'º': 'Option + K',
    '@': 'Option + ò',
    '#': 'Option + à',
    '¶': 'Option + ù',
    '∑': 'Option + Z',
    '[': 'Option + è',
    ']': 'Option + +',
    'Œ': 'Option + I',
    'π': 'Option + P',
    '·': 'Option + Shift + .',
    'É': 'Option + Shift + V',
    '}': 'Option + Shift + è',
    '{': 'Option + Shift + +',
    '±': 'Option + Shift + ì',
    'ˇ': 'Option + Shift + L',
    '¸': 'Option + Shift + .',
    '…': 'Option + ,',
    'È': 'Option + Shift + E',
    'Ù': 'Option + Shift + U',
    'Ø': 'Option + Shift + O',
    '∏': 'Option + Shift + P',
    '': 'Option + Shift + 8',
    '˛': 'Option + Shift + K',
    '‚': 'Option + Shift + Q',
    '§': 'Shift + Q',
    '◊': 'Option + Shift + ù',
    '—': 'Option + Shift + -',
    '‡': 'Option + Shift + X',
    'Ç': 'Option + Shift + ò',
    'ˇ': 'Option + Shift + L',
    '˝': 'Option + Shift + J',
    '¸': 'Option + Shift + H',
    '˚': 'Option + Shift + G',
    '˙': 'Option + Shift + F',
    '˘': 'Option + Shift + D',
    '¯': 'Option + Shift + S',
    'Ò': 'Option + Shift + T',
    'À': 'Option + Shift + W',
    '¿': 'Option + Shift + \'',
    '≈': 'Option + Shift + 0',
    '⁄': 'Option + Shift + 7',
    '›': 'Option + Shift + 6',
    '‰': 'Option + Shift + 5',
    '¢': 'Option + Shift + 4',
    '’': 'Option + Shift + 3',
    '”': 'Option + Shift + 2',
    '»': 'Option + Shift + 1',
    'Œ': 'Option + Shift + I',
    'ı': 'Option + Shift + \\',
}