word_to_symbol = {
    'tilde': '~',
    'chiocciola': '@',
    'at': '@',
    'ampersand': '&',
    'dollar': '$',
    'dollaro': '$',
    'percent': '%',
    'percentuale': '%',
    'hash': '#',
    'cancelletto': '#',
    'caret': '^',
    'circonflesso': '^',
    'asterisk': '*',
    'asterisco': '*',
    'slash': '/',
    'barra': '/',
    'backslash': '\\',
    'barra inversa': '\\',
    'pipe': '|',
    'verticale': '|',
    'underscore': '_',
    'sottolineato': '_',
    'plus': '+',
    'più': '+',
    'minus': '-',
    'meno': '-',
    'equals': '=',
    'uguale': '=',
    'question': '?',
    'punto interrogativo': '?',
    'exclamation': '!',
    'punto esclamativo': '!',
    'colon': ':',
    'due punti': ':',
    'semicolon': ';',
    'punto e virgola': ';',
    'quote': '\'',
    'apostrofo': '\'',
    'double quote': '"',
    'virgolette': '"',
    'comma': ',',
    'virgola': ',',
    'dot': '.',
    'punto': '.',
    'greater than': '>',
    'maggiore di': '>',
    'less than': '<',
    'minore di': '<',
    'bracket': '[',
    'parentesi quadra': '[',
    'bracket close': ']',
    'parentesi quadra chiusa': ']',
    'brace': '{',
    'graffa': '{',
    'brace close': '}',
    'graffa chiusa': '}',
    'paren': '(',
    'parentesi': '(',
    'paren close': ')',
    'parentesi chiusa': ')',
    'euro': '€',
    'yen': '¥',
    'pound': '£',
    'lira': '£',
    'section': '§',
    'paragrafo': '§',
    'copyright': '©',
    'registered': '®',
    'trademark': '™',
    'degree': '°',
    'gradi': '°',
    'plus-minus': '±',
    'più o meno': '±',
    'division': '÷',
    'divisione': '÷',
    'multiplication': '×',
    'moltiplicazione': '×',
    'bullet': '•',
    'pallino': '•',
    'infinity': '∞',
    'infinito': '∞',
    'partial': '∂',
    'derivata': '∂',
    'summation': '∑',
    'somma': '∑',
    'product': '∏',
    'prodotto': '∏',
    'integral': '∫',
    'integrale': '∫',
    'function': 'ƒ',
    'funzione': 'ƒ',
    'element of': '∈',
    'appartiene': '∈',
    'not equal': '≠',
    'diverso da': '≠',
    'approximately': '≈',
    'approssimativamente': '≈',
    'omega': 'Ω',
    'pi': 'π',
    'mu': 'µ',
    'sigma': 'Σ',
    'alpha': 'α',
    'beta': 'β',
    'gamma': 'γ',
    'delta': 'δ',
    'epsilon': 'ε',
    'theta': 'θ',
    'lambda': 'λ',
    'phi': 'φ',
    'psi': 'ψ',
    'chi': 'χ',
    'xi': 'ξ',
    'rho': 'ρ',
    'tau': 'τ',
    'eta': 'η',
    'upsilon': 'υ',
    'zeta': 'ζ',
    'omega majuscule': 'Ω',
}
